### ISSUE TITLE
gitlab redirect to sign_in page

### ISSUE THREAD

**Issue by cheech1440** [ethus3h/compiz-reloaded-overlay#10]
Hi

When I try to install dev-python/compizconfig-python-0.8.18 emerge try it download from gitlab, but gitlab redirect me to https://gitlab.com/users/sign_in page.

**Comment by ethus3h** [comment]
(For the record, this was fixed in https://github.com/ethus3h/compiz-reloaded-overlay/commit/3edc9986eb3fbca62c42b1d4fdb7f79503ebb9d5 per issue #9. Thanks for the report!)
