### ISSUE TITLE
PYTHON_TARGETS

### ISSUE THREAD

**Issue by dr-robertk** [ethus3h/compiz-reloaded-overlay#2]
Both, compizconfig-python and ccsm only support PYTHON_TARGETS python2_7. 
I used now python3_5 for both and it seems to work fine. Is there a particular reasons not to support later python versions?

**Comment by ethus3h** [comment]
I guess the ebuilds didn't get updated when that was added. Sorry. I'll close this once I add them. (I'm sorry also if they haven't been working well lately, have been making a lot of updates and my system doesn't yet have the merged x11-base/xorg-proto, so I haven't been able to test for a bit.)

**Comment by dr-robertk** [comment]
I just wanted to point it out. Everything seems to work fine and python2_7 is still supported. So not really an issue.

**Comment by ethus3h** [comment]
I'll still get the ebuilds updated to have Python 3 too, since the omission seems to be a mistake. If it's ok with you, I'd like to reopen this until I've put them in, just so I don't forget about it... :)

**Comment by ethus3h** [comment]
Except for compiz-boxmenu ([still appears to be Python 2–only](https://github.com/compiz-reloaded/compiz-boxmenu/blob/master/autoconfig-compiz.py)), I've added declarations for Python 3.4, 3.5, and 3.6 compatibility to the Python packages. If I missed any, feel free to ping me again. Thank you for the heads up!
