### ISSUE TITLE
compizconfig-python

### ISSUE THREAD

**Issue by jumperdos** [ethus3h/compiz-reloaded-overlay#9]
!!! Fetched file: compizconfig-python-0.8.18.tar.xz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      19086
!!! Expected: 19126
Refetching... File renamed to '/usr/portage/distfiles/compizconfig-python-0.8.18.tar.xz._checksum_failure_.jgznwofv'

Thanks in advance.

**Comment by ethus3h** [comment]
Huh, GitLab returns a redirect to a sign-in page instead of a 404 when the URL isn't found, so repoman manifest finishes without an error. Weird. Anyway, this should be fixed now. Thanks for the report, and sorry for the trouble!
